[package]
name = "drainpipe-store"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bincode = "1.3.3"
log = "0.4.22"
serde = { version = "1.0.215", features = ["derive"] }
sled = "0.34.7"
